definitions:
  main.Task:
    properties:
      name:
        type: string
      owner:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: TODO Example API
  version: "0.1"
paths:
  /tasks:
    get:
      description: Get all tasks
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Task'
            type: array
      summary: Get all tasks
swagger: "2.0"
