definitions:
  main.Task:
    properties:
      name:
        type: string
      owner:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: TODO Example API
  version: "0.1"
paths:
  /tasks:
    get:
      description: Get all tasks
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Task'
            type: array
      summary: Get all tasks
    post:
      responses:
        "200": {}
      summary: Save a task
  /tasks/{id}:
    delete:
      responses:
        "200": {}
      summary: Delete a task
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Task'
      summary: Get a task
    put:
      responses:
        "200": {}
      summary: Update a task
swagger: "2.0"
